name: Build
run-name: Build editor exe
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          # yep. this is needed now.
      - run: git clone https://github.com/re-poem/MajSimai.Extensions.git ../MajSimai.Extensions
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - run: dotnet restore MajdataEdit.csproj -r win-x64
      - run: dotnet publish MajdataEdit.csproj -c Release -f net6.0-windows7.0 -r win-x64 --no-self-contained --no-restore
      - run: ls -R
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: bin\Release\net6.0-windows7.0\win-x64\publish
