name: Build
run-name: Build editor exe
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore MajdataEdit.csproj

      - name: Build project
        run: dotnet build MajdataEdit.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish MajdataEdit.csproj -c Release -r win-x64 --no-self-contained --no-restore

      - name: List build output
        run: ls -R bin/Release/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MajdataEdit-Build
          path: bin/Release/net6.0-windows/win-x64/publish/
          if-no-files-found: error
